### ISSUE TITLE
Throws missing Path.isAbsolute method error

### ISSUE THREAD

**Issue by yngvarr992** [rapkin/gulp-bootstrap-configurator#4]
./node_modules/gulp-bootstrap-configurator/main.js:85
        var bsDir = Path.isAbsolute(opt.path) ? opt.path : Path.join(opt.base,
                         ^
TypeError: Object #<Object> has no method 'isAbsolute'
./node_modules/gulp-bootstrap-configurator/main.js:85:26

**Comment by rapkin** [comment]
I think problem is in version of node.js
