### ISSUE TITLE
Output reference Path

### ISSUE THREAD

**Issue by mqueirozcorreia** [rapkin/gulp-bootstrap-configurator#5]
Is the output expected to be generated in 'config.json' base path?

Let me show my doubt. My gulp is configured in this way:

> // For CSS 
>gulp.task('make-bootstrap-css', function () {
>    return gulp.src("./Content/BoostrapConfig/config.json")
>      .pipe(bsConfig.css())
>      .pipe(gulp.dest("./Content"));
>    // It will create `bootstrap.css` in directory `assets`. 
>});

I was expecting to the output to be generated in the './Content/bootstrap.css', but it is generated in './Content**/Content/BoostrapConfig/**bootstrap.css' instead 

I can make a pull request to change it if it is an unexpected.

**Comment by rapkin** [comment]
@mqueirozcorreia yes, in code i see that the plugin uses a path relative to 'config.json' ([this line](https://github.com/rapkin/gulp-bootstrap-configurator/blob/master/main.js#L91)). I'll make update to fix this

**Comment by mqueirozcorreia** [comment]
Nice job you did in this package!

The same behavior occurs at the js too ok?

Do you need any help with this?

All the best!

**Comment by rapkin** [comment]
@mqueirozcorreia updated (on npm also), so you can check - now all should work as expected.
